# Generated by Django 5.2.5 on 2025-08-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('experience', models.IntegerField()),
                ('profession', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=30)),
            ],
        ),
    ]
