# Generated by Django 5.2.5 on 2025-08-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_doctors_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
